services:
  - type: web
    name: freelancer-admin
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd admin && python admin_server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18 